apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.ServiceAccount.metadata.name }}
  namespace: {{ $.Release.Namespace }}
{{- if $.Values.ServiceAccount.metadata.labels }}
  labels:
    {{- $.Values.ServiceAccount.metadata.labels | trim | nindent 4 }}
{{- end }}
{{- if $.Values.ServiceAccount.metadata.annotations }}
  annotations:
    {{- $.Values.ServiceAccount.metadata.annotations | trim | nindent 4 }}
{{- end }}
